### ISSUE TITLE
Latest version is not on `deno.land/x`

### ISSUE THREAD

**Issue by timharek** [olaven/kall#24]
Latest version on [deno.land/x/kall](https://deno.land/x/kall@v0.1.0) is `v0.1.0`, which was released 4 years ago. 

Is the webhooks setup correctly or is this project not supposed to be available on `deno.land/x`? 

@olaven

**Comment by olaven** [comment]
> Is the webhooks setup correctly or is this project not supposed to be available on deno.land/x?

It's not a deliberate choice. I believe Deno's third party module system did not work like this back then, as the webhook setup (assuming [this is it](https://deno.com/add_module)) is new to me. I'll see what I can do to fix it ☺️

**Comment by olaven** [comment]
Thank you for bringing this up! I've released your latest pr (#22) as https://deno.land/x/kall@v1.0.9. 
(I also discovered some hillarious  and embarassing mistakes in prior versions, e.g. jumping from `0.0.8` to `0.0.82` 😅)
